-- AlterTable
ALTER TABLE "Arrear" ALTER COLUMN "dueDate" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "date" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "date" SET DATA TYPE TIMESTAMPTZ(6);
